FROM node:slim

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Install production dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD ["npm", "start"]